/*
 * DzglDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package shsm;

import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class DzglDialog extends javax.swing.JDialog {
	static String date;

	/** Creates new form DzglDialog */
	public DzglDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanel1.setLayout(null);

		jLabel2.setText("\u8ba2\u5355\u7f16\u53f7");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(50, 90, 70, 20);

		jLabel3.setText("\u9001\u8fbe\u5730\u5740");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(50, 140, 70, 20);

		jLabel4.setText("\u4e0b\u5355\u65f6\u95f4");
		jPanel1.add(jLabel4);
		jLabel4.setBounds(50, 190, 60, 20);

		jLabel5.setText("\u9001\u8fbe\u65f6\u95f4");
		jPanel1.add(jLabel5);
		jLabel5.setBounds(50, 240, 60, 20);

		jLabel6.setText("\u5feb\u9012\u5458\u7f16\u53f7");
		jPanel1.add(jLabel6);
		jLabel6.setBounds(50, 290, 75, 20);
		jPanel1.add(jTextField2);
		jTextField2.setBounds(150, 90, 170, 26);
		jPanel1.add(jTextField3);
		jTextField3.setBounds(150, 140, 170, 26);
		jPanel1.add(jTextField4);
		jTextField4.setBounds(150, 190, 170, 26);
		jPanel1.add(jTextField5);
		jTextField5.setBounds(150, 240, 170, 26);
		jPanel1.add(jTextField6);
		jTextField6.setBounds(150, 290, 170, 26);

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);
		jButton1.setBounds(80, 380, 63, 29);

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2);
		jButton2.setBounds(190, 380, 70, 29);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
		jTextField4.setText(time());
		jTextField4.setEditable(false);
	}

	//创建转换时间方法
	public static String time() {
		try {
			date = new SimpleDateFormat(" yyyy-MM-dd HH:mm:ss")
					.format(new java.util.Date());
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return date;
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// TODO add your handling code here:
		String orderid = jTextField2.getText().toString();
		String address = jTextField3.getText().toString();
		String start = jTextField4.getText().toString();
		String fin = jTextField5.getText().toString();
		String eID = jTextField6.getText().toString();

		String sql = "insert into deliver values (null," + orderid + ",'"
				+ address + "','" + start + "','" + fin + "'," + eID + ")";
		if (ShsmManage.runUpdate(sql)) {
			JOptionPane.showMessageDialog(null, "添加成功");
			this.dispose();
			SHSM.showTableDzgl();
		} else {
			JOptionPane.showMessageDialog(null, "添加失败");
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DzglDialog dialog = new DzglDialog(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

}